config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    root to: 'users/sessions#new'
  end
  resources :items, only: [:index, :show]
  resources :events, only: [:new, :create]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :events
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @events = Event.select("program_name")
  end

  def show

  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
.wrapper
  .tableWrap
    .tableHeader 予約一覧
    .tableIndex
      %table{border: "1", id: "targetTable"}
        %tr
          %th.theader 曜日
          %th 月
          %th 火
          %th 水
          %th 木
          %th 金
          %th 土
          %th 日
          %th 月
          %th 火
          %th 水
          %th 木
          %th 金
          %th 土
          %th 日
          %th 月
          %th 火
          %th 水
          %th 木
          %th 金
          %th 土
          %th 日
          %th 月
          %th 火
          %th 水
          %th 木
          %th 金
          %th 土
          %th 日
          %th 月
          %th 火
          %th 水
        %tr
          %th.header 機材 | 日付
          %th 01
          %th 02
          %th 03
          %th 04
          %th 05
          %th 06
          %th 07
          %th 08
          %th 09
          %th 10
          %th 11
          %th 12
          %th 13
          %th 14
          %th 15
          %th 16
          %th 17
          %th 18
          %th 19
          %th 20
          %th 21
          %th 22
          %th 23
          %th 24
          %th 25
          %th 26
          %th 27
          %th 28
          %th 29
          %th 30
          %th 31
        - @items.each_with_index do |item, i|
          %tr
            %th.eq_name
              = item.name
            %td{data:{id:i + 100}}
              = link_to "予約", new_event_path
            %td{data:{id:i + 200}}
              - @events.each do |event|
                = event.program_name
            %td{data:{id:i + 300}}
            %td{data:{id:i + 400}}
            %td{data:{id:i + 500}}
            %td{data:{id:i + 600}}
            %td{data:{id:i + 700}}
            %td{data:{id:i + 800}}
            %td{data:{id:i + 900}}
            %td{data:{id:i + 1000}}
            %td{data:{id:i + 1100}}
            %td{data:{id:i + 1200}}
            %td{data:{id:i + 1300}}
            %td{data:{id:i + 1400}}
            %td{data:{id:i + 1500}}
            %td{data:{id:i + 1600}}
            %td{data:{id:i + 1700}}
            %td{data:{id:i + 1800}}
            %td{data:{id:i + 1900}}
            %td{data:{id:i + 2000}}
            %td{data:{id:i + 2100}}
            %td{data:{id:i + 2200}}
            %td{data:{id:i + 2300}}
            %td{data:{id:i + 2400}}
            %td{data:{id:i + 2500}}
            %td{data:{id:i + 2600}}
            %td{data:{id:i + 2700}}
            %td{data:{id:i + 2800}}
            %td{data:{id:i + 2900}}
            %td{data:{id:i + 3000}}
            %td{data:{id:i + 3100}}